base_wlan_hal_types: add missing include <array>
Original Author: Dominique Martinet <dominique.martinet@atmark-techno.com>

Build fails with the following error when array is not included:
mon/beerocks/bwl/dummy/mon_wlan_hal_dummy.cpp
In file included from /code/prplMesh/common/beerocks/bwl/include/bwl/base_wlan_hal.h:13,
                 from /code/prplMesh/common/beerocks/bwl/dummy/base_wlan_hal_dummy.h:12,
                 from /code/prplMesh/common/beerocks/bwl/dummy/mon_wlan_hal_dummy.h:12,
                 from /code/prplMesh/common/beerocks/bwl/dummy/mon_wlan_hal_dummy.cpp:9:
/code/prplMesh/common/beerocks/bwl/include/bwl/base_wlan_hal_types.h:174:61: error: field 'ht_mcs_set' has incomplete type 'std::array<unsigned char, 16>'
  174 |     std::array<uint8_t, beerocks::message::HT_MCS_SET_SIZE> ht_mcs_set;
      |                                                             ^~~~~~~~~~
In file included from /usr/include/c++/12.2.1/bits/unique_ptr.h:36,
                 from /usr/include/c++/12.2.1/memory:76,
                 from /code/prplMesh/framework/tlvf/src/include/tlvf/CmduMessage.h:12,
                 from /code/prplMesh/framework/tlvf/src/include/tlvf/CmduMessageTx.h:12,
                 from /code/prplMesh/framework/tlvf/src/include/tlvf/tlvftypes.h:13,
                 from /code/prplMesh/common/beerocks/bcl/include/bcl/network/net_struct.h:16,
                 from /code/prplMesh/common/beerocks/bcl/include/bcl/beerocks_message_structs.h:13,
                 from /code/prplMesh/common/beerocks/bwl/include/bwl/base_wlan_hal_types.h:13:
/usr/include/c++/12.2.1/tuple:1595:45: note: declaration of 'struct std::array<unsigned char, 16>'
 1595 |   template<typename _Tp, size_t _Nm> struct array;
      |                                             ^~~~~
/code/prplMesh/common/beerocks/bwl/include/bwl/base_wlan_hal_types.h:179:62: error: field 'vht_mcs_set' has incomplete type 'std::array<unsigned char, 32>'
  179 |     std::array<uint8_t, beerocks::message::VHT_MCS_SET_SIZE> vht_mcs_set;
      |                                                              ^~~~~~~~~~~
/usr/include/c++/12.2.1/tuple:1595:45: note: declaration of 'struct std::array<unsigned char, 32>'
 1595 |   template<typename _Tp, size_t _Nm> struct array;
      |                                             ^~~~~
/code/prplMesh/common/beerocks/bwl/include/bwl/base_wlan_hal_types.h:185:61: error: field 'he_mcs_set' has incomplete type 'std::array<unsigned char, 32>'
  185 |     std::array<uint8_t, beerocks::message::HE_MCS_SET_SIZE> he_mcs_set;
      |                                                             ^~~~~~~~~~
/usr/include/c++/12.2.1/tuple:1595:45: note: declaration of 'struct std::array<unsigned char, 32>'
 1595 |   template<typename _Tp, size_t _Nm> struct array;
      |                                             ^~~~~

--------------
/code/prplMesh/common/beerocks/bcl/source/beerocks_os_utils.cpp: In static member function 'static std::string beerocks::os_utils::system_call_with_output(const std::string&, bool)':
/code/prplMesh/common/beerocks/bcl/source/beerocks_os_utils.cpp:79:29: error: aggregate 'std::array<char, 10000> buffer' has incomplete type and cannot be defined
   79 |     std::array<char, 10000> buffer;
      |                             ^~~~~~

--------------
/code/prplMesh/framework/platform/bpl/dhcp/linux/bpl_dhcp.cpp:24:38: error: variable 'constexpr const std::array<beerocks::bpl::dummy_lease, 3> beerocks::bpl::dummy_leases' has initializer but incomplete type
   24 | constexpr std::array<dummy_lease, 3> dummy_leases = {
      |                                      ^~~~~~~~~~~~
/code/prplMesh/framework/platform/bpl/dhcp/linux/bpl_dhcp.cpp: In function 'bool beerocks::bpl::dhcp_get_leases(leases_pair_t&)':
/code/prplMesh/framework/platform/bpl/dhcp/linux/bpl_dhcp.cpp:47:57: error: no matching function for call to 'beerocks::bpl::sIPv4Lease::sIPv4Lease(<brace-enclosed initializer list>)'
   47 |         sIPv4Lease ipv4_lease{lease.ipv4, lease.hostname};
      |                                                         ^
In file included from /code/prplMesh/framework/platform/bpl/dhcp/linux/bpl_dhcp.cpp:9:
/code/prplMesh/framework/platform/bpl/include/bpl/bpl_dhcp.h:37:5: note: candidate: 'beerocks::bpl::sIPv4Lease::sIPv4Lease(const std::string&, const std::string&)'
   37 |     sIPv4Lease(const std::string &ip_address_, const std::string &host_name_)
      |     ^~~~~~~~~~
/code/prplMesh/framework/platform/bpl/include/bpl/bpl_dhcp.h:37:5: note:   conversion of argument 1 would be ill-formed:
/code/prplMesh/framework/platform/bpl/include/bpl/bpl_dhcp.h:36:5: note: candidate: 'beerocks::bpl::sIPv4Lease::sIPv4Lease()'
   36 |     sIPv4Lease() {}
      |     ^~~~~~~~~~
/code/prplMesh/framework/platform/bpl/include/bpl/bpl_dhcp.h:36:5: note:   candidate expects 0 arguments, 2 provided
/code/prplMesh/framework/platform/bpl/include/bpl/bpl_dhcp.h:31:8: note: candidate: 'beerocks::bpl::sIPv4Lease::sIPv4Lease(const beerocks::bpl::sIPv4Lease&)'
   31 | struct sIPv4Lease {
      |        ^~~~~~~~~~
/code/prplMesh/framework/platform/bpl/include/bpl/bpl_dhcp.h:31:8: note:   candidate expects 1 argument, 2 provided
/code/prplMesh/framework/platform/bpl/include/bpl/bpl_dhcp.h:31:8: note: candidate: 'beerocks::bpl::sIPv4Lease::sIPv4Lease(beerocks::bpl::sIPv4Lease&&)'
/code/prplMesh/framework/platform/bpl/include/bpl/bpl_dhcp.h:31:8: note:   candidate expects 1 argument, 2 provided
/code/prplMesh/framework/platform/bpl/dhcp/linux/bpl_dhcp.cpp:51:91: error: no matching function for call to 'beerocks::bpl::sIPv6Lease::sIPv6Lease(<brace-enclosed initializer list>)'
   51 |         sIPv6Lease ipv6_lease{tlvf::mac_from_string(lease.mac), lease.ipv6, lease.hostname};
      |                                                                                           ^
/code/prplMesh/framework/platform/bpl/include/bpl/bpl_dhcp.h:52:5: note: candidate: 'beerocks::bpl::sIPv6Lease::sIPv6Lease(const sMacAddr&, const std::string&, const std::string&)'
   52 |     sIPv6Lease(const sMacAddr &mac_, const std::string &ip_address_, const std::string &host_name_)
      |     ^~~~~~~~~~
/code/prplMesh/framework/platform/bpl/include/bpl/bpl_dhcp.h:52:5: note:   conversion of argument 1 would be ill-formed:
/code/prplMesh/framework/platform/bpl/include/bpl/bpl_dhcp.h:51:5: note: candidate: 'beerocks::bpl::sIPv6Lease::sIPv6Lease()'
   51 |     sIPv6Lease() {}
      |     ^~~~~~~~~~
/code/prplMesh/framework/platform/bpl/include/bpl/bpl_dhcp.h:51:5: note:   candidate expects 0 arguments, 3 provided
/code/prplMesh/framework/platform/bpl/include/bpl/bpl_dhcp.h:45:8: note: candidate: 'beerocks::bpl::sIPv6Lease::sIPv6Lease(const beerocks::bpl::sIPv6Lease&)'
   45 | struct sIPv6Lease {
      |        ^~~~~~~~~~
/code/prplMesh/framework/platform/bpl/include/bpl/bpl_dhcp.h:45:8: note:   candidate expects 1 argument, 3 provided
/code/prplMesh/framework/platform/bpl/include/bpl/bpl_dhcp.h:45:8: note: candidate: 'beerocks::bpl::sIPv6Lease::sIPv6Lease(beerocks::bpl::sIPv6Lease&&)'
/code/prplMesh/framework/platform/bpl/include/bpl/bpl_dhcp.h:45:8: note:   candidate expects 1 argument, 3 provided

In file included from /code/prplMesh/controller/src/beerocks/master/db/db.h:14,
                 from /code/prplMesh/controller/src/beerocks/master/db/db.cpp:9:
/code/prplMesh/controller/src/beerocks/master/db/agent.h:126:74: error: field 'dscp_mapping_table' has incomplete type 'std::array<unsigned char, 64>'
  126 |         std::array<uint8_t, beerocks::message::DSCP_MAPPING_LIST_LENGTH> dscp_mapping_table;
      |                                                                          ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/12.2.1/bits/unique_ptr.h:36,
                 from /usr/include/c++/12.2.1/memory:76,
                 from /code/prplMesh/common/beerocks/bcl/include/bcl/beerocks_mac_map.h:13,
                 from /code/prplMesh/controller/src/beerocks/master/db/agent.h:13:
/usr/include/c++/12.2.1/tuple:1595:45: note: declaration of 'struct std::array<unsigned char, 64>'
 1595 |   template<typename _Tp, size_t _Nm> struct array;
      |                                             ^~~~~

Signed-off-by: Frederik Van Bogaert <frederik.vanbogaert@mind.be>