tools: update the alpine image
While trying to rebuild the alpine image for boardfarm, we noticed it
doesn't build anymore:
ERROR: unsatisfiable constraints:
  libffi-3.3-r2:
    conflicts: libffi-3.2.1-r6
    satisfies: llvm10-libs-10.0.1-r0[so:libffi.so.7]
  libffi-3.2.1-r6:
    conflicts: libffi-3.3-r2
    satisfies: python2-2.7.18-r0[so:libffi.so.6]

It turns out that the 'edge' repository that was added has updated
some of its packages, and they can no longer be used in our current
version.

Since 'clang-extra-tools' is now part of Alpine 3.12, just update the
base alpine image and drop the additional repository.

alpine 3.12 no longer provides python2, but now that tlvf.py runs
python3 by default, we can use it instead.

We can also remove the call to pip, since alpine has py3-yaml.

cppcheck now has a separate docker image, so we can remove it from the
Alpine image.

Signed-off-by: Raphaël Mélotte <raphael.melotte@mind.be>