common: beerocks_event_loop: add missing string include
It fixes the following error, which can occur when compiling with
Ninja with a higher number of threads:

../common/beerocks/bcl/include/bcl/beerocks_event_loop.h:60:14: error: ‘string’ in namespace ‘std’ does not name a type
   60 |         std::string name;

Signed-off-by: Raphaël Mélotte <raphael.melotte@mind.be>