beerocks/bcl/network_utils: fix flex array compilation error
Original Author: Dominique Martinet <dominique.martinet@atmark-techno.com>

g++ 7 and higher started giving an error when a flexible array member is
not at the end of a struct, making it impossible to extend
ethtool_link_settings with an anon struct like we were doing.

Convert the code to do it manually.

Fixes the following error:
In file included from /code/prplMesh/common/beerocks/bcl/source/network/network_utils.cpp:18:
/usr/include/linux/ethtool.h: In static member function 'static bool beerocks::net::network_utils::linux_iface_get_speed(const std::string&, uint32_t&, uint32_t&)':
/usr/include/linux/ethtool.h:2147:17: error: flexible array member 'ethtool_link_settings::link_mode_masks' not at end of 'struct beerocks::net::network_utils::linux_iface_get_speed(const std::string&, uint32_t&, uint32_t&)::<unnamed>'
 2147 |         __u32   link_mode_masks[];
      |                 ^~~~~~~~~~~~~~~
/code/prplMesh/common/beerocks/bcl/source/network/network_utils.cpp:992:19: note: next member '__u32 beerocks::net::network_utils::linux_iface_get_speed(const std::string&, uint32_t&, uint32_t&)::<unnamed struct>::link_mode_data [381]' declared here
  992 |             __u32 link_mode_data[3 * ETHTOOL_LINK_MODE_MASK_MAX_KERNEL_NU32];
      |                   ^~~~~~~~~~~~~~
/code/prplMesh/common/beerocks/bcl/source/network/network_utils.cpp:990:16: note: in the definition of 'struct beerocks::net::network_utils::linux_iface_get_speed(const std::string&, uint32_t&, uint32_t&)::<unnamed>'
  990 |         struct {
      |                ^

(cherry picked from commit e326b832a23e02e92c14b2396ae196f731408e44)
Signed-off-by: Frederik Van Bogaert <frederik.vanbogaert@mind.be>
(cherry picked from commit 5159d418a7c19aa1a0f9fe1561b6f96a75788786)
Signed-off-by: Frederik Van Bogaert <frederik.vanbogaert@mind.be>