Replace strncpy with snprintf to fix compile error
In feed-prpl's musl build for x86-64, this error occurs:

/home/build/openwrt/build_dir/target-x86_64_musl/prplMesh-4.0.0/controller/src/beerocks/master/son_management.cpp: In static member function 'static void son::son_management::handle_bml_message(int, std::shared_ptr<beerocks::beerocks_header>, ieee1905_1::CmduMessageTx&, son::db&, son::task_pool&)':
/home/build/openwrt/build_dir/target-x86_64_musl/prplMesh-4.0.0/controller/src/beerocks/master/son_management.cpp:2529:20: error: 'char* strncpy(char*, const char*, size_t)' specified bound 40 equals destination size [-Werror=stringop-truncation]
 2529 |             strncpy(out_stat.time_stamp, un_station.second->time_stamp.c_str(), 40);
      |             ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

By replacing the strncpy with snprintf, we resolve the UB potential of an unterminated C string,
	while retaining the desired behaviour.
It also avoids the problem of the hardcoded 40 length in the code.

Signed-off-by: Frederik Van Bogaert <frederik.vanbogaert@mind.be>
(cherry picked from commit aeaedb9bde7e78b10ff1cd44284081557617f04f)
Signed-off-by: Frederik Van Bogaert <frederik.vanbogaert@mind.be>